[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
interact_dapp = "6Ptvb7LDyA61Yz6E7b5P7bQpvfhPE4bDkaT757sGU6xH"
[programs.devnet]
interact_dapp = "6Ptvb7LDyA61Yz6E7b5P7bQpvfhPE4bDkaT757sGU6xH"
liquidity = "5uDkCoM96pwGYhAUucvCzLfm5UcjVRuxz6gH81RnRBmL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/hoangthuylinh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/main.ts"
