[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
interact_dapp = "3XVtwgUZ7P1xhMJ96yHzKaoSMGF7f1DbY4RLP7AyLLMn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hoangthuylinh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
